FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml /app/

RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    pydantic \
    pydantic-settings \
    sqlalchemy \
    psycopg2-binary \
    python-dotenv \
    email-validator

COPY ./app /app/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]