"""add linkedin url

Revision ID: 396d7f44dedd
Revises: ec7be2633db4
Create Date: 2026-07-26 02:02:28.890623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396d7f44dedd'
down_revision: Union[str, Sequence[str], None] = 'ec7be2633db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'linkedin_url')
    # ### end Alembic commands ###
