"""change skills to json

Revision ID: 468cfbc60f2d
Revises: c34c78ad7ced
Create Date: 2026-07-25 19:56:02.633424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468cfbc60f2d'
down_revision: Union[str, Sequence[str], None] = 'c34c78ad7ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_unique_constraint(None, 'candidates', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='unique')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    # ### end Alembic commands ###
